/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class fly2cam_FlyCamera */

#ifndef _Included_fly2cam_FlyCamera
#define _Included_fly2cam_FlyCamera
#ifdef __cplusplus
extern "C" {
#endif
#undef fly2cam_FlyCamera_FrameRate_15
#define fly2cam_FlyCamera_FrameRate_15 3L
#undef fly2cam_FlyCamera_FrameRate_30
#define fly2cam_FlyCamera_FrameRate_30 4L
/*
 * Class:     fly2cam_FlyCamera
 * Method:    Connect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_fly2cam_FlyCamera_Connect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     fly2cam_FlyCamera
 * Method:    NextFrame
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_fly2cam_FlyCamera_NextFrame
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     fly2cam_FlyCamera
 * Method:    Finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fly2cam_FlyCamera_Finish
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_fly2cam_FlyCamera_SetExposure
  (JNIEnv *, jobject, jint);
JNIEXPORT jint JNICALL Java_fly2cam_FlyCamera_GetExposure
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_fly2cam_FlyCamera_SetShutter
  (JNIEnv *, jobject, jint);
JNIEXPORT jint JNICALL Java_fly2cam_FlyCamera_GetShutter
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_fly2cam_FlyCamera_SetGain
  (JNIEnv *, jobject, jint);
JNIEXPORT jint JNICALL Java_fly2cam_FlyCamera_GetGain
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_fly2cam_FlyCamera_ActivateHDR
  (JNIEnv *, jobject);
_fc2Error WriteRegister
  	(int reg, int val);


#ifdef __cplusplus
}
#endif
#endif
